package adproc;
import java.awt.*;
import java.util.ArrayList;
/**
 * FlexBoxUI class to manage the design and fuctionality of the GUI
 */
public class FlexBoxUI extends javax.swing.JFrame {
    private String globalInvoice = "";
    private ArrayList<FlexBox> boxList = new ArrayList<FlexBox>();
    private double curLen;
    private double curWid;
    private double curHei;
    private int curQty;
    /**
     * Creates new form FlexBoxUI
     */
    public FlexBoxUI() {
        initComponents();
        setTitle("FlexBox Ordering System");
        setLayout(new FlowLayout());
        outputTextArea.setEditable(false);
        
    }
    /**
     *Method to update the total order price
     */
    public void updateTotalOrderPrice(){
        double newPrice = 0;
        for (int i = 0; i < boxList.size(); i++) {
            newPrice += boxList.get(i).calcPrice();
	}
        totalLabel.setText("Total Order Price: £" + String.format("%.2f", newPrice));
    }
    /**
     * Method to update the order string used as output for the customer
     */
    public void updateGlobalOrderString(){
        globalInvoice = "";
        for (int i = 0; i < boxList.size(); i++) {
            globalInvoice += "Box Order Number: " + (i+1);
            String boxStatement = boxList.get(i).orderStatement();
            globalInvoice += "\n" + boxStatement;
	}
        outputTextArea.setText(globalInvoice);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradeButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        addFeatPanel = new javax.swing.JPanel();
        addFeaLabel = new javax.swing.JLabel();
        rCornCheck = new javax.swing.JCheckBox();
        rBotCheck = new javax.swing.JCheckBox();
        sTopCheck = new javax.swing.JCheckBox();
        dimPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        width = new javax.swing.JTextField();
        widLabel = new javax.swing.JLabel();
        lenLabel = new javax.swing.JLabel();
        heiLabel = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        gradePanel = new javax.swing.JPanel();
        grade1 = new javax.swing.JRadioButton();
        grade2 = new javax.swing.JRadioButton();
        grade3 = new javax.swing.JRadioButton();
        grade4 = new javax.swing.JRadioButton();
        grade5 = new javax.swing.JRadioButton();
        gradeLabel = new javax.swing.JLabel();
        boxButtonPanel = new javax.swing.JPanel();
        addBoxBtn = new javax.swing.JButton();
        undoLastButton = new javax.swing.JButton();
        clearOptionsButton = new javax.swing.JButton();
        coloursPanel = new javax.swing.JPanel();
        numColLabel = new javax.swing.JLabel();
        coloursDrop = new javax.swing.JComboBox<>();
        qtyPanel = new javax.swing.JPanel();
        quantity = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        totalPricePanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        changeToSuitGrade = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        addFeatPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        addFeaLabel.setText("Addittional Features:");

        rCornCheck.setText("Reinforced Corners");

        rBotCheck.setText("Reinforced Botttom");

        sTopCheck.setText("Sealable Top");

        javax.swing.GroupLayout addFeatPanelLayout = new javax.swing.GroupLayout(addFeatPanel);
        addFeatPanel.setLayout(addFeatPanelLayout);
        addFeatPanelLayout.setHorizontalGroup(
            addFeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFeatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rCornCheck)
                    .addComponent(rBotCheck)
                    .addComponent(sTopCheck)
                    .addComponent(addFeaLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addFeatPanelLayout.setVerticalGroup(
            addFeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFeatPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(addFeaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rCornCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sTopCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dimPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("Dimensions (m):");

        widLabel.setText("Width");

        lenLabel.setText("Length");

        heiLabel.setText("Height");

        javax.swing.GroupLayout dimPanelLayout = new javax.swing.GroupLayout(dimPanel);
        dimPanel.setLayout(dimPanelLayout);
        dimPanelLayout.setHorizontalGroup(
            dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(dimPanelLayout.createSequentialGroup()
                        .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lenLabel)
                            .addComponent(heiLabel))
                        .addGap(18, 18, 18)
                        .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(widLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        dimPanelLayout.setVerticalGroup(
            dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lenLabel)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widLabel)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heiLabel)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gradePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        gradeButtonGroup.add(grade1);
        grade1.setText("Grade 1");

        gradeButtonGroup.add(grade2);
        grade2.setText("Grade 2");

        gradeButtonGroup.add(grade3);
        grade3.setText("Grade 3");

        gradeButtonGroup.add(grade4);
        grade4.setText("Grade 4");

        gradeButtonGroup.add(grade5);
        grade5.setText("Grade 5");

        gradeLabel.setText("Cardboard Grade:");

        javax.swing.GroupLayout gradePanelLayout = new javax.swing.GroupLayout(gradePanel);
        gradePanel.setLayout(gradePanelLayout);
        gradePanelLayout.setHorizontalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradeLabel)
                    .addGroup(gradePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grade2)
                            .addComponent(grade1)
                            .addComponent(grade3)
                            .addComponent(grade4)
                            .addComponent(grade5))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        gradePanelLayout.setVerticalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addComponent(gradeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grade2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boxButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        addBoxBtn.setText("Add Box");
        addBoxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBoxBtnActionPerformed(evt);
            }
        });

        undoLastButton.setText("Undo Last Box");
        undoLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoLastButtonActionPerformed(evt);
            }
        });

        clearOptionsButton.setText("Clear Options");
        clearOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOptionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxButtonPanelLayout = new javax.swing.GroupLayout(boxButtonPanel);
        boxButtonPanel.setLayout(boxButtonPanelLayout);
        boxButtonPanelLayout.setHorizontalGroup(
            boxButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBoxBtn)
                    .addComponent(undoLastButton)
                    .addComponent(clearOptionsButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        boxButtonPanelLayout.setVerticalGroup(
            boxButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBoxBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearOptionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoLastButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coloursPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        numColLabel.setText("Number of Colours:");

        coloursDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        javax.swing.GroupLayout coloursPanelLayout = new javax.swing.GroupLayout(coloursPanel);
        coloursPanel.setLayout(coloursPanelLayout);
        coloursPanelLayout.setHorizontalGroup(
            coloursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coloursPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(numColLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coloursDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coloursPanelLayout.setVerticalGroup(
            coloursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coloursPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(coloursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numColLabel)
                    .addComponent(coloursDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        qtyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        qtyLabel.setText("Quantity of Boxes in this style:");

        javax.swing.GroupLayout qtyPanelLayout = new javax.swing.GroupLayout(qtyPanel);
        qtyPanel.setLayout(qtyPanelLayout);
        qtyPanelLayout.setHorizontalGroup(
            qtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qtyLabel)
                .addContainerGap())
            .addGroup(qtyPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qtyPanelLayout.setVerticalGroup(
            qtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyPanelLayout.createSequentialGroup()
                .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalPricePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        totalLabel.setText("Total Order Price: £0.00");

        javax.swing.GroupLayout totalPricePanelLayout = new javax.swing.GroupLayout(totalPricePanel);
        totalPricePanel.setLayout(totalPricePanelLayout);
        totalPricePanelLayout.setHorizontalGroup(
            totalPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        totalPricePanelLayout.setVerticalGroup(
            totalPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        errorPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        errorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Error Message:");

        changeToSuitGrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeToSuitGrade.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(changeToSuitGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeToSuitGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        outputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBtn)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gradePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(boxButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(qtyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coloursPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addFeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(totalPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(dimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(addFeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(coloursPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(qtyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.getAccessibleContext().setAccessibleName("Flex Box Ordering System");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Method to clear the selected options within the GUI
     * @param evt 
     */
    private void clearOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOptionsButtonActionPerformed
        errorLabel.setText("");
        changeToSuitGrade.setText("");
        length.setText("");
        width.setText("");
        height.setText("");
        gradeButtonGroup.clearSelection();
        coloursDrop.setSelectedIndex(0);
        rBotCheck.setSelected(false);
        rCornCheck.setSelected(false);
        sTopCheck.setSelected(false);
        quantity.setText("");
    }//GEN-LAST:event_clearOptionsButtonActionPerformed
    /**
     * Method to undo the creation of the previously created FlexBox
     * @param evt 
     */
    private void undoLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoLastButtonActionPerformed
        try{
            boxList.remove(boxList.size() - 1);
            updateGlobalOrderString();
            updateTotalOrderPrice();
        }catch(Exception e){
            if(e instanceof java.lang.ArrayIndexOutOfBoundsException){
                errorLabel.setText("All boxes have been undone");
            }
        }
    }//GEN-LAST:event_undoLastButtonActionPerformed
    /**
     * Method to add a FlexBox to the total order based on the selected options within the GUI
     * @param evt 
     */
    @SuppressWarnings("empty-statement")
    private void addBoxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBoxBtnActionPerformed
        errorLabel.setText("");
        changeToSuitGrade.setText("");       
        try{//handles valid creation of a flexbox
            try{//handles validation of dimension values
                curLen = Double.valueOf(length.getText());
                curWid = Double.valueOf(width.getText());
                curHei = Double.valueOf(height.getText());
                if(
                  (curLen > 10 || curLen < 0.1) ||
                  (curWid > 10 || curWid < 0.1) ||
                  (curHei > 10 || curHei < 0.1)
                  ){
                    errorLabel.setText("Dimension must be between 0.1 - 10 metres");
                    throw new Exception();
                }
            }catch(Exception e){
                if(e instanceof NumberFormatException){
                    errorLabel.setText("Dimension values must be numerals");
                }
                throw new Exception();
            }
            double[] dim ={curLen, curWid, curHei};
            int grade;
            if(grade1.isSelected()){
                grade = 1;
            }else if (grade2.isSelected()){
                grade = 2;
            }else if (grade3.isSelected()){
                grade = 3;
            }else if (grade4.isSelected()){
                grade = 4;
            }else if (grade5.isSelected()){
                grade = 5;
            }else{
                errorLabel.setText("Card Grade must be selected");
                throw new Exception();
            }
            int colours = Integer.valueOf(coloursDrop.getSelectedItem().toString());
            boolean rBot = rBotCheck.isSelected();
            boolean rCorn = rCornCheck.isSelected();
            boolean sTop = sTopCheck.isSelected();
            try{//handles validation of the quantity value
                curQty = Integer.valueOf(quantity.getText());
                if(curQty < 1 || curQty > 100){
                    errorLabel.setText("1 - 100 boxes per order only");
                    throw new Exception();
                }
            }catch(Exception e){
                if(e instanceof NumberFormatException){
                    errorLabel.setText("Quanity value must be an integer");
                }
                throw new Exception();
            }
            FlexBox newFB = BoxOrdering.createFlexBoxOrder(dim, grade, colours, rBot, rCorn, sTop, curQty);
            if(newFB != null){
                boxList.add(newFB);
            }else{
                changeToSuitGrade.setText("");
                errorLabel.setText("We cannot make this box");
                switch(grade){//handles the error message presented to assist the user to create a valid flexbox
                    case 1: changeToSuitGrade.setText("Boxes with grade 1 card must "
                                                    + "have 0 colour and no reinforced "
                                                    + "bottom or corners.");
                            break;
                    case 2: changeToSuitGrade.setText("Boxes with grade 2 card must "
                                                    + "have 1 colour and no reinforced "
                                                    + "bottom or corners.");
                            break;
                    case 3: changeToSuitGrade.setText("Boxes with grade 3 card must "
                                                    + "have 2 colours and no reinforced "
                                                    + "bottom or corners.");
                            break;
                    case 4: changeToSuitGrade.setText("Boxes with grade 4 card must "
                                                    + "have 2 colours, a reinforced "
                                                    + "bottom, but with no reinforced corners.");
                            break;
                    case 5: changeToSuitGrade.setText("Boxes with grade 5 card must "
                                                    + "have 2 colours, a reinforeced "
                                                    + "bottom and reinforced corners.");
                            break;
                }
                throw new Exception();
            }
            // operations past here are only completed if a box has been successfully created
            errorLabel.setText("");
            changeToSuitGrade.setText("");
            updateGlobalOrderString();
            updateTotalOrderPrice();
        }catch (Exception e){}
    }//GEN-LAST:event_addBoxBtnActionPerformed
    /**
     * Button to exit the program
     * @param evt 
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
    /**
     * Main method to run the GUI which drives the program
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlexBoxUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlexBoxUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlexBoxUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlexBoxUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlexBoxUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoxBtn;
    private javax.swing.JLabel addFeaLabel;
    private javax.swing.JPanel addFeatPanel;
    private javax.swing.JPanel boxButtonPanel;
    private javax.swing.JLabel changeToSuitGrade;
    private javax.swing.JButton clearOptionsButton;
    private javax.swing.JComboBox<String> coloursDrop;
    private javax.swing.JPanel coloursPanel;
    private javax.swing.JPanel dimPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton grade1;
    private javax.swing.JRadioButton grade2;
    private javax.swing.JRadioButton grade3;
    private javax.swing.JRadioButton grade4;
    private javax.swing.JRadioButton grade5;
    private javax.swing.ButtonGroup gradeButtonGroup;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JLabel heiLabel;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lenLabel;
    private javax.swing.JTextField length;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numColLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JPanel qtyPanel;
    private javax.swing.JTextField quantity;
    private javax.swing.JCheckBox rBotCheck;
    private javax.swing.JCheckBox rCornCheck;
    private javax.swing.JCheckBox sTopCheck;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel totalPricePanel;
    private javax.swing.JButton undoLastButton;
    private javax.swing.JLabel widLabel;
    private javax.swing.JTextField width;
    // End of variables declaration//GEN-END:variables
}
